plone.meta distribution
plone/meta pull request #241
Opened 2024-12-23 10:05 UTC by gforcada

Closes #239 

Finally, I had some time to breath and decided to bite the bullet: plone.meta is born 🎉 

I'm by all means not a lawyer, and I can't remember what we decided regarding the license, I will check it up and update, but if anyone remembers, or has more knowledge about it, please share it 👍🏾

2024-12-23 10:47 UTC, gforcada commented
@stevepiercy we have a huge `config/README.md` that with this change it has 2 problems:

- it should probably be published somewhere, as it will be a proper python distribution
- it will be partially outdated and adding a bit of structure might be nicer/easier for others to read

For the publishing part an easy short cut would be to, yet again, copy what `zopefoundation/meta` repository is doing: publishing the docs on readthedocs. I can copy/adapt their configuration and wish for the best 🤞🏾 otherwise advice on what to do would be great 🙇🏾 

For the structure part I'm all open to suggestions and would be glad to get some advice. I will try my best to bend and twist the current documentation to the new proposed structure.

2024-12-23 10:55 UTC, stevepiercy commented
For a good best practice repo, check out https://github.com/plone/plone-sphinx-theme. I plan to use it for a Plone docs distribution.

I'll be offline for a couple days, but will check back later.

2025-01-06 10:27 UTC, stevepiercy requested changes
Only a minor grammar thing for the moment. Otherwise LGTM.

2025-01-06 10:32 UTC, stevepiercy commented
@gforcada I put together a PR for Plone 6 Documentation. It's a how-to guide.

- https://github.com/plone/documentation/pull/1830

We've adopted the [Diátaxis Framework](https://diataxis.fr/) for structuring docs, and we're slowly moving toward it, instead of having a mixture of all the quadrants in a page.

2025-01-14 19:33 UTC, stevepiercy requested changes

2025-01-14 19:33 UTC, stevepiercy commented on src/plone/meta/default/packages.txt
> +# Only packages in the `plone` GitHub organisation should be listed here.
US English

```suggestion
# Only packages in the `plone` GitHub organization should be listed here.
```

2025-01-14 19:33 UTC, stevepiercy commented on src/plone/meta/re_enable_actions.py
> +        print('To enable manually starting workflows clone the repository'
```suggestion
        print('To enable starting workflows manually, clone the repository'
```

2025-01-14 19:33 UTC, stevepiercy commented on src/plone/meta/re_enable_actions.py
> +              ' and run config-package on it.')
How do you do that? Should we refer to the README, so we don't have to maintain this help?

Also it's been renamed.

```suggestion
              ' and run config_package on it.')
```

2025-01-14 19:33 UTC, stevepiercy commented on src/plone/meta/re_enable_actions.py
> +                ' and run config-package on it.')
Same as previous comment.

```suggestion
                ' and run config_package on it.')
```

2025-01-14 22:47 UTC, mauritsvanrees commented on src/plone/meta/re_enable_actions.py
> +              ' and run config-package on it.')
It has not been renamed.  Well, the file has been renamed.  Ah, that would be because `config-package.py` is a fine name for a script, but it is not valid as a module name: it cannot be imported. 

But in `setup.py` the PR now registers this command:

    config-package=plone.meta.config_package:main

So this creates a `./venv/bin/config-package` script.

I have pushed a change so here in the `re_enable_actions` module we take the path of the current command (expected to be something like `./venv/bin/re-enable-actions`) and replace `re-enable-actions` with `config-package`.

2025-01-15 06:13 UTC, stevepiercy requested changes
Minor grammar fix.

2025-01-15 06:13 UTC, stevepiercy commented on src/plone/meta/re_enable_actions.py
> +                    ' files.')
```suggestion
                    ' file.')
```

2025-01-15 23:53 UTC, stevepiercy commented
AFAICT, the only thing keeping this PR from being merged is a decision on the direction of docs. I'd like to work on the docs and wrap this up, but not without a decision for their direction. I don't want to spend time on things that aren't wanted.

The options are:

1. Do nothing further and close https://github.com/plone/documentation/pull/1830.
2. Merge contents of the readmes into the root.
3. Move content of the readmes to https://github.com/plone/documentation/pull/1830, and have a single readme at the root that has a link to the docs.

@gforcada @mauritsvanrees @davisagli @ericof and anyone else who cares, what is your decision?

2025-01-26 00:28 UTC, stevepiercy commented
@gforcada @davisagli @ericof I'd still like feedback from y'all on https://github.com/plone/meta/pull/241#issuecomment-2594169103. I'm totally willing to do the work, all y'all need to do is point me in the direction to go.

@mauritsvanrees thank you for your feedback. I want one more opinion, as this is a substantial change.

2025-01-27 06:42 UTC, davisagli commented
@stevepiercy I haven't been following this one closely. What @mauritsvanrees said makes sense at a quick glance.

2025-01-30 00:03 UTC, stevepiercy commented on config/drop-legacy-python.py
@mauritsvanrees @gforcada I'm updating the README.md and found that this file was deleted and is no longer supported. Can you verify?

2025-01-30 00:04 UTC, stevepiercy reviewed
Did we drop support for `drop-legacy-python.py`?

2025-01-30 00:08 UTC, stevepiercy commented
> 2\. Merge contents of the readmes into the root.

This is now done, with the exception of the question of whether we dropped `drop-legacy-python`.

@davisagli @gforcada @mauritsvanrees @ericof one more review, pass, please? Thank you!

When this is merged, I'm going to remove most of the repetitive stuff from the related PR https://github.com/plone/documentation/pull/1830, and mostly refer to the readme.

2025-02-04 11:26 UTC, mauritsvanrees commented
> Did we drop support for `drop-legacy-python.py`?

Yes, we dropped this.  This was a left-over from when we copied the `zopefoundation/meta` repo.  It was mostly a script to help in dropping support for Python 2.  So this is no longer needed.

2025-02-04 11:36 UTC, stevepiercy approved these changes
I removed the `config/README.md` since the remaining bit for dropping Python support was dropped.

Someone else should give my work on the `/README.md` a review.

Otherwise this is ready to merge.

2025-02-04 11:41 UTC, mauritsvanrees approved these changes
I think this is ready to merge.  I have used this branch for several packages already.

2025-02-05 06:16 UTC, stevepiercy commented
@gforcada I want to merge this PR both because we think it is ready and so I can complete and merge the related PR in documentation. Please advise. Thank you!

2025-02-07 23:14 UTC, stevepiercy commented
I'm eager to merge this PR so I can merge the related PR at https://github.com/plone/documentation/pull/1830.

The final remaining item is the choice of license. I'd suggest the [default for Plone, GPL version 2](https://plone.org/foundation/copyright-licensing-logo/license-faq). @mauritsvanrees @gforcada should I push a commit to make it so?

2025-02-07 23:22 UTC, stevepiercy commented
I added the GPLv2 license.

2025-02-09 11:10 UTC, merged

2025-02-09 11:13 UTC, stevepiercy commented
@gforcada thank you! LFG!